apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-service
  namespace: hotel-booking
  labels:
    app: hotel-booking
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"  # ‚Üê CHANGE TO "elb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: hotel-booking
    version: blue
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080