apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-service
  namespace: hotel-booking
spec:
  selector:
    app: hotel-booking
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
