apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-system-blue
  namespace: hotel-booking
  labels:
    app: hotel-booking-system
    version: blue
spec:
  selector:
    app: hotel-booking-system
    version: blue
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
